service: proy3

frameworkVersion: '2'

plugins:
 - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-west-2

functions:
  consultarAlumno:
    handler: handler.generic
    events:
      - httpApi:
          path: /
          method: get
      - httpApi:
          path: /{proxy+}
          method: get
  registrarAlumno:
    handler: handler.generic
    events:
      - httpApi:
          path: /
          method: post
      - httpApi:
          path: /{proxy+}
          method: post
  eliminarAlumno:
    handler: handler.generic
    events:
      - httpApi:
          path: /
          method: delete
      - httpApi:
          path: /{proxy+}
          method: delete